[package]
name = "solution"
version = "0.1.0"
authors = [
  "Jonas Heinrich",
]
default-run = "solution"
edition = "2021"

[dependencies]
# Faster parallel hashmap
hashbrown = "0.15"
# Util for getting the number of CPUs
num_cpus = "1.14"
